// Microorganism database
const microorganisms = [
    {
        "name": "Staphylococcus aureus",
        "type": "Bacteria",
        "cultureStain": "Gram, Mannitol salt agar",
        "structure": "G(+), coccus",
        "keyDiagnostics": "Catalase(+), Coagulase(+)",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human (Respiratory), Food",
        "treatment": "Nafcillin, Oxacillin, Dicloxacillin, Vancomycin, Linezolid"
    },
    {
        "name": "Staphylococcus epidermidis",
        "type": "Bacteria",
        "cultureStain": "Gram, Mannitol salt agar",
        "structure": "G(+), coccus",
        "keyDiagnostics": "Catalase(+), Urease(+), Coagulase(-), Novobiocin-sensitive",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human (skin)",
        "treatment": "Vancomycin"
    },
    {
        "name": "Staphylococcus saprophyticus",
        "type": "Bacteria",
        "cultureStain": "Gram, Mannitol salt agar",
        "structure": "G(+), coccus",
        "keyDiagnostics": "Catalase(+), Urease(+), Coagulase(-), Novobiocin-resistant",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human (GI, GU)",
        "treatment": "Vancomycin"
    },
    {
        "name": "Streptococcus agalactiae",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar",
        "structure": "G(+), coccus",
        "keyDiagnostics": "Hippuricase(+), Beta-Hemolytic, Bacitracin-resistant, PYR(-)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human (GI/Vagina)",
        "treatment": "Penicillin G"
    },
    {
        "name": "Streptococcus pneumoniae",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar",
        "structure": "G(+), lancet-shaped diplococcus",
        "keyDiagnostics": "Catalase(-), Alpha-hemolytic, Optochin-sensitive, ",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "GI (Respiratory)",
        "treatment": "Ceftriaxone/Azithromycin"
    },
    {
        "name": "Streptococcus pyogenes",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar",
        "structure": "G(+), coccus",
        "keyDiagnostics": "Streptokinase(+), DNase-B(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human (throat, skin)",
        "treatment": "Penicillin"
    },
    {
        "name": "Streptococcus viridans",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar",
        "structure": "G(+), coccus",
        "keyDiagnostics": "Catalase(-), Alpha-hemolytic, Optochin-resistant, LAP(+), PYR(-) ",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Human (GI/GU/Oral/Skin)",
        "treatment": "Penicillin G/Ceftriaxone"
    },
    {
        "name": "Streptococcus gallolyticus",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar, 6.5% NaCl(-)",
        "structure": "G(+), coccus",
        "keyDiagnostics": "Catalase(-), ",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human",
        "treatment": "Penicillin G/Ceftriaxone+Gentamicin"
    },
    {
        "name": "Enterococcus faecalis",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar, 6.5% NaCl(+)",
        "structure": "G(+), cocci",
        "keyDiagnostics": "Gamma-Hemolytic, Catalase (-), PYR(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Can Be Encapsulated",
        "siteHost": "Human (GI)",
        "treatment": "Penicillins+Aminoglycosides/Linezolid/Daptomycin"
    },
    {
        "name": "Enterococcus faecium ",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar, 6.5% NaCl(+)",
        "structure": "G(+), cocci",
        "keyDiagnostics": "Gamma-Hemolytic, Catalase (-), PYR(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Can Be Encapsulated",
        "siteHost": "Human (GI)",
        "treatment": "Linezolid/Tigecycline/Daptomycin"
    },
    {
        "name": "Bacillus anthracis ",
        "type": "Bacteria",
        "cultureStain": "Gram",
        "structure": "G(+), spore-forming, bacilli",
        "keyDiagnostics": "Toxin, D-glutamate(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Cattle, Soil",
        "treatment": "Fluoroquinolones/Doxycycline"
    },
    {
        "name": "Clostridium tetani",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar",
        "structure": "G(+), spore-forming, bacilli",
        "keyDiagnostics": "Toxin",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Rusted Metal, Soil, Feces",
        "treatment": "Human Tetanus Immune Globulin"
    },
    {
        "name": "Clostridium botulinum",
        "type": "Bacteria",
        "cultureStain": "Gram",
        "structure": "G(+), spore-forming, bacilli",
        "keyDiagnostics": "Toxin",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Canned Foods, Dust, Soil",
        "treatment": "BabyBIG/Antitoxin"
    },
    {
        "name": "Clostridium perfringens",
        "type": "Bacteria",
        "cultureStain": "Gram",
        "structure": "G(+), spore-forming, club-shaped bacilli",
        "keyDiagnostics": "Lecithinase(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Soil, Reheated meats",
        "treatment": "Piperacillin-Tazobactam + Clindamycin/Fidoxamicin/Vancomycin"
    },
    {
        "name": "Clostridioides difficile",
        "type": "Bacteria",
        "cultureStain": "Gram",
        "structure": "G(+), spore-forming, bacilli",
        "keyDiagnostics": "Glutamate Dehydrogenase(+)",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human (GI)",
        "treatment": "Vancomycin, Metronidazole"
    },
    {
        "name": "Corynebacterium diphtheriae",
        "type": "Bacteria",
        "cultureStain": "Gram, Cysteine-tellurite agar, L\u00f6ffler medium",
        "structure": "G(+), club-shaped bacilli ",
        "keyDiagnostics": "Toxin",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Human (Respiratory/Skin)",
        "treatment": "Diphtheria antitoxin + Penicillin/Erythromycin"
    },
    {
        "name": "Listeria monocytogenes",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar",
        "structure": "G(+), bacilli ",
        "keyDiagnostics": "Catalase(+), Beta-Hemolytic",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Milk, Cheese, Deli Meat",
        "treatment": "Ampicillin"
    },
    {
        "name": "Actinomyces israelii",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar",
        "structure": "G(+), Filamentous bacilli",
        "keyDiagnostics": "",
        "intraExtra": "Extracellular ",
        "capsuleEnvelope": "No",
        "siteHost": "Human (Oral)",
        "treatment": "Penicillins, Tetracyclines"
    },
    {
        "name": "Nocardia asteroides",
        "type": "Bacteria",
        "cultureStain": "Ziehl-Neelsen (acid fast)",
        "structure": "G(+), Filamentous bacilli",
        "keyDiagnostics": "Catalase(+), Urease(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Soil, Dust, Water, Plants",
        "treatment": "TMP-SMX"
    },
    {
        "name": "Neisseria meningitidis",
        "type": "Bacteria",
        "cultureStain": "Gram, Thayer-Martin (VPN) medium",
        "structure": "G(-), diplococcus",
        "keyDiagnostics": "Toxin, IgA Protease(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Soil, Huma (Respiratory)",
        "treatment": "Ceftriaxone/Penicillin G"
    },
    {
        "name": "Neisseria gonorrhoeae",
        "type": "Bacteria",
        "cultureStain": "Gram, Thayer-Martin (VPN) medium",
        "structure": "G(-), diplococcus",
        "keyDiagnostics": "Oxidase(+)",
        "intraExtra": "Facultative intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Human (GU)",
        "treatment": "Ceftriaxone, Azithromycin"
    },
    {
        "name": "Moraxella catarrhalis",
        "type": "Bacteria",
        "cultureStain": "Gram, Chocolate agar",
        "structure": "G(-), diplococcus",
        "keyDiagnostics": "Catalase(+), Oxidase(+), DNase(+)",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Human (Respiratory)",
        "treatment": "Amoxicillin, \u00b1Clavulanic acid"
    },
    {
        "name": "Klebsiella pneumoniae",
        "type": "Bacteria",
        "cultureStain": "Gram, MacConkey agar",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Urease(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Soil, Water, Human, Hospitals",
        "treatment": "Imipenem-Cilastin, Aztreonam"
    },
    {
        "name": "Salmonella typhi",
        "type": "Bacteria",
        "cultureStain": "Gram, Hektoen agar",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Urease(-)",
        "intraExtra": "Facultative Intracellular ",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human",
        "treatment": "Fluoroquinolones"
    },
    {
        "name": "Shigella dysenteriae",
        "type": "Bacteria",
        "cultureStain": "Gram, Hektoen agar",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Catalase(+), Urease(-), Oxidase(-), Toxin",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Human (GI), Feces",
        "treatment": "Fluoroquinolones/Cephalosporins/Ampicillins"
    },
    {
        "name": "Escherichia coli",
        "type": "Bacteria",
        "cultureStain": "Gram, MacConkey agar, EMB agar",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Catalase(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Feces, Meats, Animals, Human",
        "treatment": "Supportive Care/Nitrofurantoin/TMP-SMX/Ciprofloxacin"
    },
    {
        "name": "Yersinia pestis",
        "type": "Bacteria",
        "cultureStain": "Gram, Giemsa stain",
        "structure": "G(-), coccobacilli",
        "keyDiagnostics": "Oxidase(-), Coagulase(+)",
        "intraExtra": "Facultative Intracellular ",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Rat, prairie dog, flea",
        "treatment": "Aminoglycosides, fluoroquinolones"
    },
    {
        "name": "Campylobacter jejuni",
        "type": "Bacteria",
        "cultureStain": "Gram, Skirrow's agar",
        "structure": "G(-), curved bacilli",
        "keyDiagnostics": "Oxidase(+)",
        "intraExtra": "Facultative Intracellular ",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Poultry, Cattle, Dogs",
        "treatment": "Macrolides/Fluoroginolones"
    },
    {
        "name": "Vibrio cholerae",
        "type": "Bacteria",
        "cultureStain": "Gram, TCBS agar",
        "structure": "G(-), curved bacilli",
        "keyDiagnostics": "Mucinase(+)",
        "intraExtra": "Facultative Intracellular ",
        "capsuleEnvelope": "Can be Encapsulated ",
        "siteHost": "Contaminated Water",
        "treatment": "Doxycycline + Rehydration"
    },
    {
        "name": "Helicobacter pylori",
        "type": "Bacteria",
        "cultureStain": "Gram, Silver",
        "structure": "G(-), curved bacilli",
        "keyDiagnostics": "Urease(+)",
        "intraExtra": "Facultative Intracellular ",
        "capsuleEnvelope": "No",
        "siteHost": "Human (Stomach)",
        "treatment": "PPI, Amoxicillin/Metronidazole, Clarithromycin"
    },
    {
        "name": "Proteus mirabilis",
        "type": "Bacteria",
        "cultureStain": "Gram, Low Salt agar",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Catalase(+), Urease(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Human (GI), Animals",
        "treatment": "Fluoroquinolones, TMP-SMX"
    },
    {
        "name": "Bordatella pertussis",
        "type": "Bacteria",
        "cultureStain": "Gram, Regan-Lowe, Bordet-Gengou agar",
        "structure": "G(-), coccobacilli",
        "keyDiagnostics": "Toxin, Filamentous Hemagglutinin(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human (Respiratory)",
        "treatment": "Macrolides "
    },
    {
        "name": "Haemophilus influenzae",
        "type": "Bacteria",
        "cultureStain": "Gram, Chocolate agar",
        "structure": "G(-), coccobacillus",
        "keyDiagnostics": "V-Factor, Hematin, IgA Protease",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Can be Encapsulated",
        "siteHost": "Human (Respiratory)",
        "treatment": "Amoxicillin, Ampicillin, \u00b1Clavulanic acid, Ceftriaxone"
    },
    {
        "name": "Pseudomonas aerigunosa",
        "type": "Bacteria",
        "cultureStain": "Gram, Cetrimide agar",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Catalase(+), Oxidase(+), Phospholipase C(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Soil, Water, Plants, Animals, Hospitals",
        "treatment": "Piperacillin/Ceftazidime/Cefepime/Levofloxacillin/Aztreonam/Imipenem-Cilastin"
    },
    {
        "name": "Burkholderia cepacia",
        "type": "Bacteria",
        "cultureStain": "Gram",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Urease(+), MLST",
        "intraExtra": "Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Soil, water",
        "treatment": "Ceftazidime, Carbapenem, TMP-SMX"
    },
    {
        "name": "Bartonella henselae",
        "type": "Bacteria",
        "cultureStain": "Gram, Warthin-Starry, Silver",
        "structure": "G(-), coccobacilli ",
        "keyDiagnostics": "IFA, ELISA",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Cats",
        "treatment": "Azithromycin (immunocompetent), Doxycycline/Erythromycin (immunocompromoised)"
    },
    {
        "name": "Brucella spp",
        "type": "Bacteria",
        "cultureStain": "Gram, Ziehl-Neelsen (acid fast)",
        "structure": "G(-), pleomorphic, coccobacilli ",
        "keyDiagnostics": "ELISA",
        "intraExtra": "Facultative Intracellular ",
        "capsuleEnvelope": "No",
        "siteHost": "Farm Animals, Unpasteurized Dairy",
        "treatment": "Doxycycline + Rifampin"
    },
    {
        "name": "Francisella tularensis",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar, Thayer-Martin (VPN) medium",
        "structure": "G(-), coccobacilli ",
        "keyDiagnostics": "ELISA, Lysine Decarboxylase(+)",
        "intraExtra": "Facultative Intracellular ",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Tick, Deerfly, Rabbits",
        "treatment": "Tetracyclines"
    },
    {
        "name": "Pasteurella multocida",
        "type": "Bacteria",
        "cultureStain": "Gram, Sheep blood agar, Bipolar",
        "structure": "G(-), coccobacilli ",
        "keyDiagnostics": "Oxidase(+), Catalase(+), Urease(-)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated ",
        "siteHost": "Dogs, Cats",
        "treatment": "Penicillin G "
    },
    {
        "name": "Borrelia burgdorferi",
        "type": "Bacteria",
        "cultureStain": "Giemsa, Wright stain",
        "structure": "Spirochete",
        "keyDiagnostics": "ELISA",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Ticks",
        "treatment": "Doxycycline, Ceftriaxone"
    },
    {
        "name": "Ehrlichia chaffeensis",
        "type": "Bacteria",
        "cultureStain": "Giemsa, Wright stain",
        "structure": "G(-), pleomorphic",
        "keyDiagnostics": "PCR, IFA",
        "intraExtra": "Obligate Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Lone Star Tick",
        "treatment": "Tetracyclines"
    },
    {
        "name": "Anaplasma phagocytophilum",
        "type": "Bacteria",
        "cultureStain": "Giemsa, Wright stain, Diff-Quik",
        "structure": "G(-), pleomorphic",
        "keyDiagnostics": "PCR, IFA",
        "intraExtra": "Obligate Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Ixodes Tick",
        "treatment": "Tetracyclines"
    },
    {
        "name": "Rickettsia rickettsii",
        "type": "Bacteria",
        "cultureStain": "Gram, Giemsa, Gimenez",
        "structure": "G(-), coccobacilli",
        "keyDiagnostics": "PCR, IFA, ELISA",
        "intraExtra": "Obligate Intracellular ",
        "capsuleEnvelope": "Outer Slime Layer",
        "siteHost": "Ticks",
        "treatment": "Tetracyclines"
    },
    {
        "name": "Mycobacterium tuberculosis",
        "type": "Bacteria",
        "cultureStain": "Ziehl-Neelsen (acid fast), L\u00f6wenstein-Jensen",
        "structure": "Bacillus",
        "keyDiagnostics": "KatG(+), InhA(+), Blac(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Soil, Water, Human",
        "treatment": "RIPE, Rifampin, Isoniazid, Pyrazinamide, Ethambutol,"
    },
    {
        "name": "Mycobacterium leprae",
        "type": "Bacteria",
        "cultureStain": "Ziehl-Neelsen (acid fast)",
        "structure": "Bacillus",
        "keyDiagnostics": "PGL-I, PCR",
        "intraExtra": "Obligate Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Soil, Water, Armadillos, Human, Red Squirrels",
        "treatment": "Dapsone, Rifampin, Clofazimine "
    },
    {
        "name": "Mycobacterium avium-intracellulare complex",
        "type": "Bacteria",
        "cultureStain": "Ziehl-Neelsen (acid fast)",
        "structure": "Bacillus",
        "keyDiagnostics": "GPL, PCR",
        "intraExtra": "Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Animals, Water, Soil, Dust",
        "treatment": "Macrolide, Ethambutol, Rifabutin (for immunocompromised)"
    },
    {
        "name": "Leptospira interrogans",
        "type": "Bacteria",
        "cultureStain": "Silver, Warthin-Starry, Dark field microscopy",
        "structure": "G(-), Spirochete",
        "keyDiagnostics": "PCR, ELISA",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "Periplasmic Space",
        "siteHost": "Contaminated Water",
        "treatment": "Doxycycline (Mild), Penicillin G (Severe)"
    },
    {
        "name": "Treponema pallidum",
        "type": "Bacteria",
        "cultureStain": "Silver, Dark field microscopy",
        "structure": "G(-), Spirochete",
        "keyDiagnostics": "RPR/VDRL",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Periplasmic Space",
        "siteHost": "Human",
        "treatment": "Penicillin G "
    },
    {
        "name": "Chlamydia spp",
        "type": "Bacteria",
        "cultureStain": "Gram, Giemsa",
        "structure": "G(-), pleomorphic",
        "keyDiagnostics": "PCR, ELISA",
        "intraExtra": "Obligate Intracellular ",
        "capsuleEnvelope": "No",
        "siteHost": "Human",
        "treatment": "Tetracyclines"
    },
    {
        "name": "Coxiella burnetti",
        "type": "Bacteria",
        "cultureStain": "Gram, Gimenez stain",
        "structure": "G(-), pleomorphic",
        "keyDiagnostics": "PCR, ELISA, IFA",
        "intraExtra": "Obligate Intracellular ",
        "capsuleEnvelope": "No",
        "siteHost": "Cattle/Sheep/Goats",
        "treatment": "Tetracyclines"
    },
    {
        "name": "Gardnerella vaginalis",
        "type": "Bacteria",
        "cultureStain": "Gram-variable, Human Blood Bilayer agar",
        "structure": "Coccobacillus",
        "keyDiagnostics": "Sialidase(+), PIP(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "No",
        "siteHost": "Human (GU)",
        "treatment": "Clindamycin/Metronidazole"
    },
    {
        "name": "Mycoplasma pneumoniae",
        "type": "Bacteria",
        "cultureStain": "Eaton agar",
        "structure": "Pleomorphic",
        "keyDiagnostics": "PCR, ELISA",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Can be Encapsulated",
        "siteHost": "Human (Respiratory)",
        "treatment": "Macrolides/Fluoroquinolones/Doxycycline"
    },
    {
        "name": "Legionella pneumophila",
        "type": "Bacteria ",
        "cultureStain": "Gram, Silver stain, Charcoal yeast extract",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Oxidase(+)",
        "intraExtra": "Intracellular ",
        "capsuleEnvelope": "No",
        "siteHost": "Water Sources ",
        "treatment": "Macrolides/Fluoroquinolones"
    },
    {
        "name": "Burkholderia pseudomallei",
        "type": "Bacteria ",
        "cultureStain": "Gram, Bipolar staining",
        "structure": "G(-), bacillus",
        "keyDiagnostics": "Catalase(+), Oxidase(+), Phospholipase(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated ",
        "siteHost": "Contaminated Soil/Water/Dust",
        "treatment": "Ceftazidime, Carbapenem, TMP-SMX, Meropenem"
    },
    {
        "name": "Trophyrema whipplei",
        "type": "Bacteria",
        "cultureStain": "Gram, Periodic Acid-Schiff",
        "structure": "G(+), bacillus",
        "keyDiagnostics": "PCR, PAS(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Soil, Sewage, Feces",
        "treatment": "Ceftriaxone, TMP-SMX"
    },
    {
        "name": "Haemophilus ducreyi",
        "type": "Bacteria",
        "cultureStain": "Gram, Chocolate agar",
        "structure": "G(-), Coccobacillus",
        "keyDiagnostics": "Catalase(-), Oxidase(+), Hemin(+)",
        "intraExtra": "Extracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Human",
        "treatment": "Azithromycin/Ceftriaxone"
    },
    {
        "name": "Vibrio fulnificus",
        "type": "Bacteria",
        "cultureStain": "Gram, VV Agar",
        "structure": "G(-), Curved, Bacillus",
        "keyDiagnostics": "Metalloproteinase(+), Hemolysin(+), Lecithinase(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Encapsulated",
        "siteHost": "Contaminated Seafood",
        "treatment": "Doxycycline+Ceftriaxone"
    },
    {
        "name": "Bacillus cereus ",
        "type": "Bacteria",
        "cultureStain": "Gram, PEMBA",
        "structure": "G(+), spore-forming, bacilli",
        "keyDiagnostics": "Catalase(+)",
        "intraExtra": "Facultative Intracellular",
        "capsuleEnvelope": "Can be Encapsulated",
        "siteHost": "Reheated Rice",
        "treatment": "Supportive Care/Vancomycin"
    }
];
